export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string;
          email: string;
          display_name: string | null;
          postcode: string | null;
          state: string | null;
          suburb: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          display_name?: string | null;
          postcode?: string | null;
          state?: string | null;
          suburb?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          display_name?: string | null;
          postcode?: string | null;
          state?: string | null;
          suburb?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      car_listings: {
        Row: {
          id: string;
          source: 'carsales' | 'gumtree';
          source_id: string;
          source_url: string;
          make: string;
          model: string;
          variant: string | null;
          year: number;
          price: number;
          odometer: number | null;
          transmission: string | null;
          fuel_type: string | null;
          body_type: string | null;
          drive_type: string | null;
          colour: string | null;
          engine_size: number | null;
          cylinders: number | null;
          seller_state: string;
          seller_postcode: string | null;
          seller_suburb: string | null;
          seller_type: string | null;
          seller_name: string | null;
          title: string;
          description: string | null;
          images: string[];
          features: string[];
          first_scraped_at: string;
          last_scraped_at: string;
          is_active: boolean;
          scrape_count: number;
        };
        Insert: {
          id?: string;
          source: 'carsales' | 'gumtree';
          source_id: string;
          source_url: string;
          make: string;
          model: string;
          variant?: string | null;
          year: number;
          price: number;
          odometer?: number | null;
          transmission?: string | null;
          fuel_type?: string | null;
          body_type?: string | null;
          drive_type?: string | null;
          colour?: string | null;
          engine_size?: number | null;
          cylinders?: number | null;
          seller_state: string;
          seller_postcode?: string | null;
          seller_suburb?: string | null;
          seller_type?: string | null;
          seller_name?: string | null;
          title: string;
          description?: string | null;
          images?: string[];
          features?: string[];
          first_scraped_at?: string;
          last_scraped_at?: string;
          is_active?: boolean;
          scrape_count?: number;
        };
        Update: {
          id?: string;
          source?: 'carsales' | 'gumtree';
          source_id?: string;
          source_url?: string;
          make?: string;
          model?: string;
          variant?: string | null;
          year?: number;
          price?: number;
          odometer?: number | null;
          transmission?: string | null;
          fuel_type?: string | null;
          body_type?: string | null;
          drive_type?: string | null;
          colour?: string | null;
          engine_size?: number | null;
          cylinders?: number | null;
          seller_state?: string;
          seller_postcode?: string | null;
          seller_suburb?: string | null;
          seller_type?: string | null;
          seller_name?: string | null;
          title?: string;
          description?: string | null;
          images?: string[];
          features?: string[];
          first_scraped_at?: string;
          last_scraped_at?: string;
          is_active?: boolean;
          scrape_count?: number;
        };
      };
      saved_searches: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          search_criteria: Json;
          delivery_postcode: string;
          delivery_state: string;
          email_alerts: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          search_criteria: Json;
          delivery_postcode: string;
          delivery_state: string;
          email_alerts?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          search_criteria?: Json;
          delivery_postcode?: string;
          delivery_state?: string;
          email_alerts?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      saved_cars: {
        Row: {
          id: string;
          user_id: string;
          listing_id: string;
          delivery_postcode: string;
          delivery_state: string;
          calculated_costs: Json;
          total_delivered_price: number;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          listing_id: string;
          delivery_postcode: string;
          delivery_state: string;
          calculated_costs: Json;
          total_delivered_price: number;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          listing_id?: string;
          delivery_postcode?: string;
          delivery_state?: string;
          calculated_costs?: Json;
          total_delivered_price?: number;
          notes?: string | null;
          created_at?: string;
        };
      };
      transport_routes: {
        Row: {
          id: string;
          from_state: string;
          to_state: string;
          base_price: number;
          per_km_rate: number;
          estimated_days_min: number;
          estimated_days_max: number;
          notes: string | null;
          last_updated: string;
        };
        Insert: {
          id?: string;
          from_state: string;
          to_state: string;
          base_price: number;
          per_km_rate: number;
          estimated_days_min: number;
          estimated_days_max: number;
          notes?: string | null;
          last_updated?: string;
        };
        Update: {
          id?: string;
          from_state?: string;
          to_state?: string;
          base_price?: number;
          per_km_rate?: number;
          estimated_days_min?: number;
          estimated_days_max?: number;
          notes?: string | null;
          last_updated?: string;
        };
      };
      postcodes: {
        Row: {
          postcode: string;
          suburb: string;
          state: string;
          latitude: number | null;
          longitude: number | null;
        };
        Insert: {
          postcode: string;
          suburb: string;
          state: string;
          latitude?: number | null;
          longitude?: number | null;
        };
        Update: {
          postcode?: string;
          suburb?: string;
          state?: string;
          latitude?: number | null;
          longitude?: number | null;
        };
      };
      scrape_jobs: {
        Row: {
          id: string;
          source: string;
          job_type: 'full' | 'incremental' | 'specific';
          status: 'pending' | 'running' | 'completed' | 'failed';
          search_query: string | null;
          listings_found: number;
          listings_new: number;
          listings_updated: number;
          listings_removed: number;
          error_message: string | null;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          source: string;
          job_type: 'full' | 'incremental' | 'specific';
          status?: 'pending' | 'running' | 'completed' | 'failed';
          search_query?: string | null;
          listings_found?: number;
          listings_new?: number;
          listings_updated?: number;
          listings_removed?: number;
          error_message?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          source?: string;
          job_type?: 'full' | 'incremental' | 'specific';
          status?: 'pending' | 'running' | 'completed' | 'failed';
          search_query?: string | null;
          listings_found?: number;
          listings_new?: number;
          listings_updated?: number;
          listings_removed?: number;
          error_message?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
      };
      marketplace_listings: {
        Row: {
          id: string;
          user_id: string;
          make: string;
          model: string;
          variant: string | null;
          year: number;
          price: number;
          odometer: number | null;
          transmission: 'automatic' | 'manual' | 'cvt' | 'dct' | 'other' | null;
          fuel_type: 'petrol' | 'diesel' | 'electric' | 'hybrid' | 'plug-in-hybrid' | 'lpg' | 'other' | null;
          body_type: 'sedan' | 'hatchback' | 'suv' | 'wagon' | 'ute' | 'van' | 'coupe' | 'convertible' | 'other' | null;
          drive_type: 'fwd' | 'rwd' | 'awd' | '4wd' | 'other' | null;
          colour: string | null;
          engine_size: string | null;
          cylinders: number | null;
          rego_expiry: string | null;
          vin: string | null;
          seller_state: string;
          seller_postcode: string;
          seller_suburb: string | null;
          contact_name: string;
          contact_email: string;
          contact_phone: string | null;
          show_phone: boolean;
          title: string;
          description: string | null;
          features: string[];
          has_rwc: boolean;
          has_rego: boolean;
          is_negotiable: boolean;
          status: 'draft' | 'pending' | 'active' | 'sold' | 'expired' | 'removed';
          views_count: number;
          enquiries_count: number;
          created_at: string;
          updated_at: string;
          published_at: string | null;
          expires_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          make: string;
          model: string;
          variant?: string | null;
          year: number;
          price: number;
          odometer?: number | null;
          transmission?: 'automatic' | 'manual' | 'cvt' | 'dct' | 'other' | null;
          fuel_type?: 'petrol' | 'diesel' | 'electric' | 'hybrid' | 'plug-in-hybrid' | 'lpg' | 'other' | null;
          body_type?: 'sedan' | 'hatchback' | 'suv' | 'wagon' | 'ute' | 'van' | 'coupe' | 'convertible' | 'other' | null;
          drive_type?: 'fwd' | 'rwd' | 'awd' | '4wd' | 'other' | null;
          colour?: string | null;
          engine_size?: string | null;
          cylinders?: number | null;
          rego_expiry?: string | null;
          vin?: string | null;
          seller_state: string;
          seller_postcode: string;
          seller_suburb?: string | null;
          contact_name: string;
          contact_email: string;
          contact_phone?: string | null;
          show_phone?: boolean;
          title: string;
          description?: string | null;
          features?: string[];
          has_rwc?: boolean;
          has_rego?: boolean;
          is_negotiable?: boolean;
          status?: 'draft' | 'pending' | 'active' | 'sold' | 'expired' | 'removed';
          views_count?: number;
          enquiries_count?: number;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
          expires_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          make?: string;
          model?: string;
          variant?: string | null;
          year?: number;
          price?: number;
          odometer?: number | null;
          transmission?: 'automatic' | 'manual' | 'cvt' | 'dct' | 'other' | null;
          fuel_type?: 'petrol' | 'diesel' | 'electric' | 'hybrid' | 'plug-in-hybrid' | 'lpg' | 'other' | null;
          body_type?: 'sedan' | 'hatchback' | 'suv' | 'wagon' | 'ute' | 'van' | 'coupe' | 'convertible' | 'other' | null;
          drive_type?: 'fwd' | 'rwd' | 'awd' | '4wd' | 'other' | null;
          colour?: string | null;
          engine_size?: string | null;
          cylinders?: number | null;
          rego_expiry?: string | null;
          vin?: string | null;
          seller_state?: string;
          seller_postcode?: string;
          seller_suburb?: string | null;
          contact_name?: string;
          contact_email?: string;
          contact_phone?: string | null;
          show_phone?: boolean;
          title?: string;
          description?: string | null;
          features?: string[];
          has_rwc?: boolean;
          has_rego?: boolean;
          is_negotiable?: boolean;
          status?: 'draft' | 'pending' | 'active' | 'sold' | 'expired' | 'removed';
          views_count?: number;
          enquiries_count?: number;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
          expires_at?: string | null;
        };
      };
      listing_images: {
        Row: {
          id: string;
          listing_id: string;
          user_id: string;
          storage_path: string;
          url: string;
          file_name: string;
          file_size: number;
          mime_type: string;
          width: number | null;
          height: number | null;
          sort_order: number;
          is_primary: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          listing_id: string;
          user_id: string;
          storage_path: string;
          url: string;
          file_name: string;
          file_size: number;
          mime_type: string;
          width?: number | null;
          height?: number | null;
          sort_order?: number;
          is_primary?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          listing_id?: string;
          user_id?: string;
          storage_path?: string;
          url?: string;
          file_name?: string;
          file_size?: number;
          mime_type?: string;
          width?: number | null;
          height?: number | null;
          sort_order?: number;
          is_primary?: boolean;
          created_at?: string;
        };
      };
      listing_enquiries: {
        Row: {
          id: string;
          listing_id: string;
          user_id: string | null;
          name: string;
          email: string;
          phone: string | null;
          message: string;
          delivery_state: string | null;
          delivery_postcode: string | null;
          is_read: boolean;
          replied_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          listing_id: string;
          user_id?: string | null;
          name: string;
          email: string;
          phone?: string | null;
          message: string;
          delivery_state?: string | null;
          delivery_postcode?: string | null;
          is_read?: boolean;
          replied_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          listing_id?: string;
          user_id?: string | null;
          name?: string;
          email?: string;
          phone?: string | null;
          message?: string;
          delivery_state?: string | null;
          delivery_postcode?: string | null;
          is_read?: boolean;
          replied_at?: string | null;
          created_at?: string;
        };
      };
    };
  };
};

// Helper types
export type MarketplaceListing = Database['public']['Tables']['marketplace_listings']['Row'];
export type MarketplaceListingInsert = Database['public']['Tables']['marketplace_listings']['Insert'];
export type ListingImage = Database['public']['Tables']['listing_images']['Row'];
export type ListingEnquiry = Database['public']['Tables']['listing_enquiries']['Row'];
